# Welcome to DATA5000 - Week 1

This week we will look into how to use Google Colab, load and work with files, and the library **pandas**

In [ ]:
from google.colab import files
import pandas as pd
import io
uploaded = files.upload()

Saving aus_cpi.csv to aus_cpi.csv

In [ ]:

df = pd.read_csv(io.BytesIO(uploaded['aus_cpi.csv']))

In [ ]:
df.head(10) # have a look at the top 10 records

        Date   AU-CPI
0   1/1/1960  2.73973
1   1/4/1960  4.10959
2   1/7/1960  4.05405
3  1/10/1960  4.00000
4   1/1/1961  4.00000
5   1/4/1961  3.94737
6   1/7/1961  1.29870
7  1/10/1961  0.00000
8   1/1/1962  0.00000
9   1/4/1962 -1.26582

Question: How to look at the top 8 records ?
Type the code in the cell bellow:

In [ ]:
df.tail(1) # Look at the bottom 1 record

         Date   AU-CPI
253  1/4/2023  6.02696

In [ ]:
df.describe() # understand the distribution of the data

           AU-CPI
count  254.000000
mean     4.706993
std      3.811989
min     -1.265820
25%      2.040785
50%      3.260870
75%      7.112592
max     17.692310

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    254 non-null    object
 1   AU-CPI  254 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.1+ KB

In [ ]:
df.columns # what are the columns in our dataset ?

Index(['Date', 'AU-CPI'], dtype='object')

**How to select a column ?**

In [ ]:
df['AU-CPI']

0      2.73973
1      4.10959
2      4.05405
3      4.00000
4      4.00000
        ...
249    6.14478
250    7.26817
251    7.83182
252    7.02179
253    6.02696
Name: AU-CPI, Length: 254, dtype: float64

**Now, whats the median of the Inflation ?**

In [ ]:
df['AU-CPI'].median() # Whats the median value of the inflation ?

3.26087

In [ ]:
df.shape # Whats the shape of our data ?

(254, 2)

In [ ]:
df.dtypes # What datatypes are our columns

Date       object
AU-CPI    float64
dtype: object

**A lot of models will require the Date column to be a format of date/datetime**

Pandas provide a lot of methods to change the datatype. In the example bellow we change the column Date to be a DateTime.

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    254 non-null    datetime64[ns]
 1   AU-CPI  254 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.1 KB

In [ ]:
# Try and change the datatype of the column AU-CPI to be integer

# Ask your lecturer to tell you what the difference between integer and float is ?

In [ ]:
# Now double check that the change was successful

In [ ]:
# Lastly change the datatype back to its original float type